trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndDeploy
  workspace:
    clean: all

  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'

  - script: dotnet restore
    displayName: Restore dependencies

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: Build project

  - script: dotnet test --no-build
    displayName: Run tests

  - script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    displayName: Publish project

  - task: CopyFiles@2
    displayName: Deploy to IIS folder
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**'
      TargetFolder: 'C:\inetpub\bankingapp'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'

  - script: iisreset
    displayName: Restart IIS